global:
  scrape_interval: 10s
  evaluation_interval: 10s

rule_files:
  - rules/rules.yaml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: "prometheus:9090"

  - job_name: "tempo"
    static_configs:
      - targets: ["tempo:3200"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: "tempo:3200"

  - job_name: "grafana"
    static_configs:
      - targets: ["grafana:3000"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: "grafana:3000"

  - job_name: "alertmanager"
    static_configs:
      - targets: ["alertmanager:9093"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: "alertmanager:9093"

  - job_name: "order-service"
    static_configs:
      - targets: ["order-service:5001"]

  - job_name: "payment-service"
    static_configs:
      - targets: ["payment-service:5002"]
    metrics_path: /process_payment

  - job_name: "docker"
    static_configs:
      - targets: ["192.124.0.1:9323"]

  - job_name: "cicd"
    static_configs:
      - targets: ["10.10.120.21:9323"]

  - job_name: "api-gateway"
    static_configs:
      - targets: ["10.10.120.126"]
    metrics_path: /rrmmpytfgbvjwwiwclozuvonqt/metrics
    # relabel_configs:
    #   - source_labels: [__address__]
    #     target_label: __param_target
    #   - source_labels: [__param_target]
    #     target_label: instance
    #   - target_label: __address__
    #     # replacement: "10.10.120.126/rrmmpytfgbvjwwiwclozuvonqt/metrics"
